name: torch_new
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - pandas
  - pip:
    - torch-summary
    - numpy
