name: torch_bench
channels:
  - pytorch-nightly
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - jupyter
  - jupyterlab
  - pip:
      - pandas
      - torch
      - torchvision
      - torchaudio
