name: torch_new
channels:
  - pytorch-nightly
  - conda-forge
dependencies:
  - python=3.11
  - pip:
      - torch
      - torchvision
      - torchaudio
      - torch-summary
      - numpy
      - marshmallow
